title: Bitcasa Help Center
subtitle: Bitcasa Support
author: Justin
description: Find answers to common questions

auto: true
source: .
exclude: .gitignore, .sass-cache, _drafts, public, Gemfile, Gemfile.lock, Rakefile, README.md

permalink: /:categories/:title
markdown: rdiscount
pygments: true